[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/djiwandou/netlify-go-sse-function-demo"
  GO111MODULE = "on"

[[redirects]]
  from = "/sse/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
